import type { LandingSpec } from '../schemas/landing-spec.js';

/**
 * Детерминированный renderer: LandingSpec → TSX-строка.
 *
 * На этапе 1 это простой mapper component-name → JSX. Никакого LLM на этом
 * шаге — модель только генерит spec, а сборка TSX из spec'а — чистая функция,
 * чтобы результат был воспроизводим и проверяем.
 *
 * На этапе 6 (handoff) сгенерированный TSX пакуется в ZIP как самодостаточный
 * файл для разработчика.
 */

const INDENT = '  ';

function jsxString(value: string): string {
  return `"${value.replace(/"/g, '\\"')}"`;
}

function renderCta(value: { label: string; href: string }): string {
  return `{ label: ${jsxString(value.label)}, href: ${jsxString(value.href)} }`;
}

function renderVisual(value: {
  type: string;
  assetId?: string;
}): string {
  return `{ type: ${jsxString(value.type)} }`;
}

function renderHeroSection(props: {
  eyebrow?: string;
  title: string;
  subtitle: string;
  primaryCta: { label: string; href: string };
  secondaryCta?: { label: string; href: string } | null;
  visual?: { type: string; assetId?: string } | null;
}): string {
  const parts: string[] = [];
  if (props.eyebrow) parts.push(`${INDENT}eyebrow=${jsxString(props.eyebrow)}`);
  parts.push(`${INDENT}title=${jsxString(props.title)}`);
  parts.push(`${INDENT}subtitle=${jsxString(props.subtitle)}`);
  parts.push(`${INDENT}primaryCta={${renderCta(props.primaryCta)}}`);
  if (props.secondaryCta) {
    parts.push(`${INDENT}secondaryCta={${renderCta(props.secondaryCta)}}`);
  }
  if (props.visual) {
    parts.push(`${INDENT}visual={${renderVisual(props.visual)}}`);
  }
  return `<HeroSection\n${parts.join('\n')}\n/>`;
}

const SECTION_RENDERERS: Record<string, (props: never) => string> = {
  HeroSection: renderHeroSection as (props: never) => string,
};

export function renderLandingToTSX(spec: LandingSpec, slug: string): string {
  const usedComponents = new Set<string>();
  const sectionJSX: string[] = [];

  for (const section of spec.sections) {
    const renderer = SECTION_RENDERERS[section.component];
    if (!renderer) {
      throw new Error(
        `Unknown component "${section.component}" in section ${section.id}. ` +
          `Зарегистрируйте его в packages/harness/src/render/render-landing.ts`,
      );
    }
    usedComponents.add(section.component);
    sectionJSX.push(renderer(section.props as never));
  }

  const imports = [...usedComponents].sort().join(', ');

  return `// AUTO-GENERATED by @buffalo/harness — do not edit by hand
// slug: ${slug}
// pageType: ${spec.pageType}
// goal: ${spec.goal}

import { ${imports} } from '@buffalo/ui/landing';

export const metadata = {
  title: ${jsxString(spec.seo.title)},
  description: ${jsxString(spec.seo.description)},
};

export default function Landing_${slug.replace(/[^a-zA-Z0-9_]/g, '_')}() {
  return (
    <main>
${sectionJSX.map((s) => s.split('\n').map((l) => INDENT + INDENT + l).join('\n')).join('\n\n')}
    </main>
  );
}
`;
}
