// AUTO-GENERATED by @buffalo/harness — illustration buffalo-hero-dashboard (deterministic stub)
import type { SVGProps } from 'react';

interface InnerProps extends SVGProps<SVGSVGElement> {
  dark: boolean;
}

function Inner({ dark, ...props }: InnerProps) {
  return (
    <svg
      viewBox="0 -220 2150 1420"
      xmlns="http://www.w3.org/2000/svg"
      role="img"
      aria-label="buffalo-hero-dashboard hero illustration"
      {...props}
    >
      <defs>
        <radialGradient id={`glow-${dark ? 'd' : 'l'}`} cx="1500" cy="380" r="580" gradientUnits="userSpaceOnUse">
          <stop offset="0%"   stopColor={dark ? '#7D4CCF' : '#EFE9F9'} stopOpacity={0.55} />
          <stop offset="100%" stopColor={dark ? '#7D4CCF' : '#EFE9F9'} stopOpacity={0} />
        </radialGradient>
      </defs>
      <rect
        x={0} y={-220} width={2150} height={1420}
        fill={`url(#glow-${dark ? 'd' : 'l'})`}
      />
      <rect
        x={387} y={312.4}
        width={1376} height={710}
        rx={32}
        fill={dark ? '#0F172A' : '#FFFFFF'}
        stroke={dark ? '#334155' : '#E2E8F0'}
        strokeWidth={2}
      />
      <text
        x={473}
        y={482.8}
        fill={dark ? '#E2E8F0' : '#0F172A'}
        fontSize={48}
        fontWeight={600}
        className="tabular-nums"
      >
        12 345
      </text>
      <circle
        cx={1677}
        cy={397.6}
        r={28}
        fill={dark ? '#7D4CCF' : '#7D4CCF'}
      />
    </svg>
  );
}

export default function BuffaloHeroDashboard(props: SVGProps<SVGSVGElement>) {
  return (
    <>
      <Inner dark={false} className="dark:hidden" {...props} />
      <Inner dark={true} className="hidden dark:block" {...props} />
    </>
  );
}
