import type { IllustrationSpec } from '../schemas/illustration-spec.js';

/**
 * Детерминированный TSX-stub иллюстрации, который заведомо проходит AST-валидатор
 * (один root <svg>, dark-prop, -d/-l id, dual-render, нет transparent stops).
 *
 * Назначение:
 *   1. `--no-llm` режим CLI для тестов/CI;
 *   2. структурный шаблон, на который опирается LLM-промпт (одна и та же форма).
 */
export function pascalCase(id: string): string {
  return id
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((p) => (p.charAt(0).toUpperCase() + p.slice(1)))
    .join('');
}

export function renderIllustrationStub(spec: IllustrationSpec): string {
  const Name = pascalCase(spec.id);
  const accent = spec.palette.accent;
  const glowD = spec.palette.glowDark;
  const glowL = spec.palette.glowLight;
  const vb = spec.viewBox;

  return `// AUTO-GENERATED by @buffalo/harness — illustration ${spec.id} (deterministic stub)
import type { SVGProps } from 'react';

interface InnerProps extends SVGProps<SVGSVGElement> {
  dark: boolean;
}

function Inner({ dark, ...props }: InnerProps) {
  return (
    <svg
      viewBox="${vb.x} ${vb.y} ${vb.width} ${vb.height}"
      xmlns="http://www.w3.org/2000/svg"
      role="img"
      aria-label="${spec.id} hero illustration"
      {...props}
    >
      <defs>
        <radialGradient id={\`glow-\${dark ? 'd' : 'l'}\`} cx="${spec.glow.centerX}" cy="${spec.glow.centerY}" r="${spec.glow.radius}" gradientUnits="userSpaceOnUse">
          <stop offset="0%"   stopColor={dark ? '${glowD}' : '${glowL}'} stopOpacity={0.55} />
          <stop offset="100%" stopColor={dark ? '${glowD}' : '${glowL}'} stopOpacity={0} />
        </radialGradient>
      </defs>
      <rect
        x={${vb.x}} y={${vb.y}} width={${vb.width}} height={${vb.height}}
        fill={\`url(#glow-\${dark ? 'd' : 'l'})\`}
      />
      <rect
        x={${vb.width * 0.18}} y={${vb.height * 0.22}}
        width={${vb.width * 0.64}} height={${vb.height * 0.5}}
        rx={32}
        fill={dark ? '#0F172A' : '#FFFFFF'}
        stroke={dark ? '#334155' : '#E2E8F0'}
        strokeWidth={2}
      />
      <text
        x={${vb.width * 0.22}}
        y={${vb.height * 0.34}}
        fill={dark ? '#E2E8F0' : '#0F172A'}
        fontSize={48}
        fontWeight={600}
        className="tabular-nums"
      >
        12 345
      </text>
      <circle
        cx={${vb.width * 0.78}}
        cy={${vb.height * 0.28}}
        r={28}
        fill={dark ? '${accent}' : '${accent}'}
      />
    </svg>
  );
}

export default function ${Name}(props: SVGProps<SVGSVGElement>) {
  return (
    <>
      <Inner dark={false} className="dark:hidden" {...props} />
      <Inner dark={true} className="hidden dark:block" {...props} />
    </>
  );
}
`;
}

export function renderIllustrationStory(spec: IllustrationSpec): string {
  const Name = pascalCase(spec.id);
  return `import type { Meta, StoryObj } from '@storybook/react';
import ${Name} from './${Name}.js';

const meta: Meta<typeof ${Name}> = {
  title: 'Illustrations/${Name}',
  component: ${Name},
  parameters: { layout: 'fullscreen' },
};

export default meta;

export const Light: StoryObj<typeof ${Name}> = {
  render: () => (
    <div className="bg-white p-8">
      <${Name} className="w-full max-w-5xl mx-auto" />
    </div>
  ),
};

export const Dark: StoryObj<typeof ${Name}> = {
  render: () => (
    <div className="dark bg-slate-950 p-8">
      <${Name} className="w-full max-w-5xl mx-auto" />
    </div>
  ),
};
`;
}
